# 使用docker-compose up -d运行
version: '3'

services:
  server:
    image: docker.udolphin.com/wiki/server:1.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./config/config.json:/app/config/config.json
    depends_on:
      - db  
    environment:
      - NODE_ENV=production
  db:
    image: docker.io/mongo
    restart: on-failure:5
#    ports:
#      - "27018:27017"
