# 使用docker-compose up -d运行
version: '3'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    container_name: admin-mongo
    volumes:
      - ./data:/data
      - ./config:/config
